# Generated by Django 4.2.3 on 2023-09-05 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=256)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=256)),
                ('offset_eq', models.BooleanField(default=False)),
                ('offset_hq', models.BooleanField(default=False)),
                ('reference', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.session')),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_name', models.CharField(max_length=12)),
                ('aim', models.BooleanField(default=False)),
                ('cal', models.BooleanField(default=False)),
                ('foc', models.BooleanField(default=False)),
                ('val_time', models.FloatField(default=10)),
                ('first_time', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.session')),
            ],
        ),
        migrations.CreateModel(
            name='Integrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_name', models.CharField(max_length=12)),
                ('on', models.BooleanField(default=False)),
                ('onoff', models.BooleanField(default=False)),
                ('fsw', models.BooleanField(default=False)),
                ('skydids', models.BooleanField(default=False)),
                ('wobbler', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.session')),
            ],
        ),
        migrations.CreateModel(
            name='Febe_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('febe_name', models.CharField(choices=[('febe1', 'Febe1'), ('febe2', 'Febe2'), ('febe3', 'Febe3'), ('febe4', 'Febe4')], max_length=10)),
                ('description', models.CharField(max_length=256)),
                ('sb1_pol1', models.BooleanField(default=False)),
                ('sb1_pol2', models.BooleanField(default=False)),
                ('sb2_pol1', models.BooleanField(default=False)),
                ('sb2_pol2', models.BooleanField(default=False)),
                ('sb3_pol1', models.BooleanField(default=False)),
                ('sb3_pol2', models.BooleanField(default=False)),
                ('sb4_pol1', models.BooleanField(default=False)),
                ('sb4_pol2', models.BooleanField(default=False)),
                ('sb5_pol1', models.BooleanField(default=False)),
                ('sb5_pol2', models.BooleanField(default=False)),
                ('sb6_pol1', models.BooleanField(default=False)),
                ('sb6_pol2', models.BooleanField(default=False)),
                ('sb7_pol1', models.BooleanField(default=False)),
                ('sb7_pol2', models.BooleanField(default=False)),
                ('sb8_pol1', models.BooleanField(default=False)),
                ('sb8_pol2', models.BooleanField(default=False)),
                ('all_sb_pol1', models.BooleanField(default=False)),
                ('all_sb_pol2', models.BooleanField(default=False)),
                ('oscillator_min', models.FloatField(default=22.0)),
                ('oscillator_max', models.FloatField(default=47.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.session')),
            ],
        ),
    ]
