# Generated by Django 4.2.3 on 2023-09-11 06:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FebeParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('sb1_pol1', models.BooleanField(default=False)),
                ('sb1_pol2', models.BooleanField(default=False)),
                ('sb2_pol1', models.BooleanField(default=False)),
                ('sb2_pol2', models.BooleanField(default=False)),
                ('sb3_pol1', models.BooleanField(default=False)),
                ('sb3_pol2', models.BooleanField(default=False)),
                ('sb4_pol1', models.BooleanField(default=False)),
                ('sb4_pol2', models.BooleanField(default=False)),
                ('sb5_pol1', models.BooleanField(default=False)),
                ('sb5_pol2', models.BooleanField(default=False)),
                ('sb6_pol1', models.BooleanField(default=False)),
                ('sb6_pol2', models.BooleanField(default=False)),
                ('sb7_pol1', models.BooleanField(default=False)),
                ('sb7_pol2', models.BooleanField(default=False)),
                ('sb8_pol1', models.BooleanField(default=False)),
                ('sb8_pol2', models.BooleanField(default=False)),
                ('all_sb_pol1', models.BooleanField(default=False)),
                ('all_sb_pol2', models.BooleanField(default=False)),
                ('oscillator', models.FloatField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Febes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('febe_name', models.CharField(max_length=10)),
                ('num_pol', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=4)])),
                ('num_sb', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.MaxValueValidator(limit_value=8)])),
                ('max_lo', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=8.0), django.core.validators.MaxValueValidator(limit_value=110.0)])),
                ('min_lo', models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=8.0), django.core.validators.MaxValueValidator(limit_value=110.0)])),
            ],
        ),
        migrations.DeleteModel(
            name='Febe_parameters',
        ),
        migrations.AddField(
            model_name='febeparameters',
            name='febe_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.febes'),
        ),
        migrations.AddField(
            model_name='febeparameters',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.session'),
        ),
    ]
