# Generated by Django 4.2.3 on 2023-09-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_febeparameters_febes_delete_febe_parameters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sources',
            name='offset_eq',
        ),
        migrations.RemoveField(
            model_name='sources',
            name='offset_hq',
        ),
        migrations.AddField(
            model_name='sources',
            name='offset',
            field=models.CharField(choices=[('offset1', 'eq'), ('offset2', 'hq')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sources',
            name='offset_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sources',
            name='offset_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sources',
            name='reference_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sources',
            name='reference_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='febes',
            name='febe_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='sources',
            name='reference',
            field=models.CharField(choices=[('reference1', 'eq'), ('reference2', 'hq')], max_length=12),
        ),
    ]
