# Generated by Django 4.2.3 on 2023-11-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_remove_sources_offset_eq_remove_sources_offset_hq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='aim',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='cal',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='foc',
        ),
        migrations.RemoveField(
            model_name='sources',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='sources',
            name='offset_x',
        ),
        migrations.RemoveField(
            model_name='sources',
            name='offset_y',
        ),
        migrations.RemoveField(
            model_name='sources',
            name='reference_x',
        ),
        migrations.RemoveField(
            model_name='sources',
            name='reference_y',
        ),
        migrations.AddField(
            model_name='sources',
            name='offset_eq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sources',
            name='offset_hq',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sources',
            name='reference',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Foc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foc_name', models.CharField(max_length=12)),
                ('single_return', models.BooleanField(default=False)),
                ('samples_number', models.IntegerField(default=200)),
                ('foc_time', models.IntegerField(default=10)),
                ('foc_lenght', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.session')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.setup')),
            ],
        ),
        migrations.CreateModel(
            name='Cal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_name', models.CharField(max_length=12)),
                ('calibra', models.BooleanField(default=False)),
                ('cal_time', models.IntegerField(default=10)),
                ('order', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.session')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.setup')),
            ],
        ),
        migrations.CreateModel(
            name='Aim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim_name', models.CharField(max_length=12)),
                ('x_axis', models.FloatField(default=0)),
                ('y_axis', models.FloatField(default=0)),
                ('z_axis', models.FloatField(default=0)),
                ('tilt_x', models.FloatField(default=0)),
                ('tilt_y', models.FloatField(default=0)),
                ('single_return', models.BooleanField(default=False)),
                ('samples_number', models.IntegerField(default=200)),
                ('aim_time', models.FloatField(default=10)),
                ('order', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.session')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.setup')),
            ],
        ),
    ]
