# Generated by Django 4.2.3 on 2023-07-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='telescop_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.TextField(blank=True, null=True)),
                ('frontends', models.TextField(blank=True, null=True)),
                ('febename', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
    ]
