# Generated by Django 4.2.3 on 2023-07-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telescop_parameters',
            name='config_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='telescop_parameters',
            name='febename',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='telescop_parameters',
            name='frontends',
            field=models.CharField(max_length=10),
        ),
    ]
