# Generated by Django 4.2.3 on 2023-07-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager_app', '0002_alter_telescop_parameters_config_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='febe_parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('febe_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='sb_oscillator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='sb_pol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pol_1', models.BooleanField()),
                ('pol_2', models.BooleanField()),
            ],
        ),
    ]
