# Generated by Django 4.2.3 on 2023-07-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager_app', '0005_alter_febe_parameters_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='febe_parameters',
            name='description',
            field=models.CharField(default=2, max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='febe_parameters',
            name='session_id',
            field=models.CharField(max_length=12),
        ),
    ]
