# Generated by Django 4.2.3 on 2023-07-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager_app', '0006_febe_parameters_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='febe_parameters',
            name='description',
            field=models.CharField(max_length=72),
        ),
    ]
