# Generated by Django 4.2.3 on 2023-07-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager_app', '0010_alter_febe_parameters_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ColorChoice',
        ),
        migrations.RenameField(
            model_name='sb_pol',
            old_name='pol_1',
            new_name='pol',
        ),
        migrations.RemoveField(
            model_name='sb_pol',
            name='pol_2',
        ),
        migrations.AddField(
            model_name='febe_parameters',
            name='sb_pol_1',
            field=models.CharField(default=2, max_length=12),
            preserve_default=False,
        ),
    ]
