# Generated by Django 4.2.3 on 2023-07-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager_app', '0016_alter_febe_parameters_sb1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='febe_parameters',
            old_name='SB1',
            new_name='SB1_POL1',
        ),
        migrations.AddField(
            model_name='febe_parameters',
            name='SB1_POL2',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
