# Generated by Django 4.2.3 on 2023-07-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager_app', '0019_febe_parameters_oscillator_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='febe_parameters',
            name='source',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
