# Generated by Django 4.2.3 on 2023-07-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager_app', '0020_febe_parameters_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='febe_parameters',
            name='offset_eq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='febe_parameters',
            name='offset_hq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='febe_parameters',
            name='reference',
            field=models.FloatField(default=0.0),
        ),
    ]
