# Generated by Django 4.2.3 on 2023-07-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_manager_app', '0021_febe_parameters_offset_eq_febe_parameters_offset_hq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='febe_parameters',
            name='aim',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='febe_parameters',
            name='cal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='febe_parameters',
            name='first_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='febe_parameters',
            name='foc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='febe_parameters',
            name='fsw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='febe_parameters',
            name='on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='febe_parameters',
            name='onoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='febe_parameters',
            name='skydids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='febe_parameters',
            name='val_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='febe_parameters',
            name='wobbler',
            field=models.BooleanField(default=False),
        ),
    ]
